# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Restaurants4Square' do
pod 'ObjectMapper', '~> 1.2'
end

